apiVersion: v1
data:
  DB_DATABASE: restaubot_database
  DB_ENGINE: django.db.backends.postgresql
  DB_HOST: db
  DB_PASSWORD: pu4_YKKfcU3nc*b
  DB_PORT: "5432"
  DB_USER: moham21
  DEBUG: "1"
  DJANGO_ALLOWED_HOSTS: '[]'
  SECRET_KEY: foo
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: web-env
  name: web-env
